#!/bin/bash 

### Setting the arguments
arg1="install"
arg2="uninstall"
arg3="remove"
arg4="sync"
arg5="update"
arg6="live-update"
arg7="search"

### Checking if the config file exists and using it when available
if test -f /etc/bastet/config; then
    zugaina="$(cat /etc/bastet/config | grep zugaina | cut -c 11-)"
    eixcheck="$(cat /etc/bastet/config | grep eix | cut -c 7-)"
else
    zugaina=true
    eixcheck=true
fi

### Checking if eix is installed
if [ "$eixcheck" == true ]; then
    if test -f /usr/bin/eix; then
        eix=true
    else
        eix=false
    fi
fi

### checking and executing arguments
if [ "$1" == "$arg1" ]; then
    shift
    emerge -av $*
elif [ "$1" == "$arg2" ]; then
    shift
    emerge -a --depclean $*
elif [ "$1" == "$arg3" ]; then
    shift
    emerge -aC $*
elif [ "$1" == "$arg4" ]; then
    if [ "$eix" == true ]; then
        eix-sync
    else
        emerge --sync
    fi
elif [ "$1" == "$arg5" ]; then
    emerge -avuND @world
elif [ "$1" == "$arg6" ]; then
    if test -f /usr/bin/smart-live-rebuild1; then
        smart-live-rebuild
    else
        printf "%s\n" "You don't have 'smart-live-rebuild' installed!"
    fi
elif [ "$1" == "$arg7" ]; then
    if [ "$eix" == true ]; then
        shift
        eix -R $*
        if [ "$zugaina" == true ]; then
            printf "\n"
            printf "%s\n" "Zugaina search:"
            printf "%s\n" "http://gpo.zugaina.org/Search?search=$*"
        fi
    else
        shift
        emerge --search $*
        if [ "$zugaina" == true ]; then
            printf "\n"
            printf "%s\n" "Zugaina search:"
            printf "%s\n" "http://gpo.zugaina.org/Search?search=$*"
        fi
    fi
fi
