#!/bin/bash 

arg1="install"
arg2="uninstall"
arg3="remove"
arg4="sync"
arg5="update"
arg6="live-update"
arg7="search"

### Checking if eix is installed
if test -f /usr/bin/eix; then
    eix=1
else
    eix=0
fi

if [ "$1" == "$arg1" ]; then
    shift
    emerge -av $*
elif [ "$1" == "$arg2" ]; then
    shift
    emerge -a --depclean $*
elif [ "$1" == "$arg3" ]; then
    shift
    emerge -aC $*
elif [ "$1" == "$arg4" ]; then
    if [ "$eix" == 1 ]; then
        eix-sync
    else
        emerge --sync
    fi
elif [ "$1" == "$arg5" ]; then
    emerge -avuND @world
elif [ "$1" == "$arg6" ]; then
    smart-live-rebuild
elif [ "$1" == "$arg7" ]; then
    if [ "$eix" == 1 ]; then
        shift
        eix -R $*
    else
        shift
        emerge --search $*
    fi
fi
