#!/bin/bash 

arg1="install"
arg2="uninstall"
arg3="remove"
arg4="sync"
arg5="update"
arg6="live-update"
arg7="search"
zugaina=1
eixcheck=1

### Checking if eix is installed
if [ "$eixcheck" == 1 ]; then
    if test -f /usr/bin/eix; then
        eix=1
    else
        eix=0
    fi
fi

### checking and executing arguments
if [ "$1" == "$arg1" ]; then
    shift
    emerge -av $*
elif [ "$1" == "$arg2" ]; then
    shift
    emerge -a --depclean $*
elif [ "$1" == "$arg3" ]; then
    shift
    emerge -aC $*
elif [ "$1" == "$arg4" ]; then
    if [ "$eix" == 1 ]; then
        eix-sync
    else
        emerge --sync
    fi
elif [ "$1" == "$arg5" ]; then
    emerge -avuND @world
elif [ "$1" == "$arg6" ]; then
    smart-live-rebuild
elif [ "$1" == "$arg7" ]; then
    if [ "$eix" == 1 ]; then
        shift
        eix -R $*
        if [ "$zugaina" == 1 ]; then
            printf "\n"
            printf "%s\n" "Zugaina search:"
            printf "%s\n" "http://gpo.zugaina.org/Search?search=$*"
        fi
    else
        shift
        emerge --search $*
        if [ "$zugaina" == 1 ]; then
            printf "\n"
            printf "%s\n" "Zugaina search:"
            printf "%s\n" "http://gpo.zugaina.org/Search?search=$*"
        fi
    fi
fi
